// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyTaiSan.Data;

#nullable disable

namespace WebQuanLyTaiSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401090615_Category")]
    partial class Category
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8995), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 1",
                            IsDeleted = false,
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9002), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 2",
                            IsDeleted = false,
                            Name = "Linh kiện rời"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9005), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 3",
                            IsDeleted = false,
                            Name = "Thiết bị mạng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9008), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 4",
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9011), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 5",
                            IsDeleted = false,
                            Name = "Máy in"
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9015), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 6",
                            IsDeleted = false,
                            Name = "Máy chiếu"
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9018), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 7",
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9021), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 8",
                            IsDeleted = false,
                            Name = "Thiết bị lưu trữ"
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9026), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 9",
                            IsDeleted = false,
                            Name = "Thiết bị loại 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9032), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 10",
                            IsDeleted = false,
                            Name = "Thiết bị loại 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9037), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 11",
                            IsDeleted = false,
                            Name = "Thiết bị loại 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9040), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 12",
                            IsDeleted = false,
                            Name = "Thiết bị loại 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9044), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 13",
                            IsDeleted = false,
                            Name = "Thiết bị loại 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9047), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 14",
                            IsDeleted = false,
                            Name = "Thiết bị loại 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9050), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 15",
                            IsDeleted = false,
                            Name = "Thiết bị loại 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9053), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 16",
                            IsDeleted = false,
                            Name = "Thiết bị loại 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9057), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 17",
                            IsDeleted = false,
                            Name = "Thiết bị loại 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9063), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 18",
                            IsDeleted = false,
                            Name = "Thiết bị loại 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9067), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 19",
                            IsDeleted = false,
                            Name = "Thiết bị loại 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9072), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 20",
                            IsDeleted = false,
                            Name = "Thiết bị loại 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ComputerId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(199), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 600000.0,
                            SerialNumber = "SN-878F36BE",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ComputerId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(209), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 700000.0,
                            SerialNumber = "SN-3AD3254B",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(216), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 800000.0,
                            SerialNumber = "SN-AEA2F8DB",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ComputerId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(222), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 900000.0,
                            SerialNumber = "SN-0A819956",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ComputerId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(227), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1000000.0,
                            SerialNumber = "SN-9CF86FE0",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(245), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1100000.0,
                            SerialNumber = "SN-D576322D",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ComputerId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(326), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1200000.0,
                            SerialNumber = "SN-CB5D58F3",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ComputerId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(332), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1300000.0,
                            SerialNumber = "SN-C966B277",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(338), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1400000.0,
                            SerialNumber = "SN-822CD38D",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ComputerId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(351), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1500000.0,
                            SerialNumber = "SN-FEEB0575",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ComputerId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(359), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1600000.0,
                            SerialNumber = "SN-7FEE89CE",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(389), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1700000.0,
                            SerialNumber = "SN-961E54B6",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ComputerId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(398), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1800000.0,
                            SerialNumber = "SN-79CD9D0A",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ComputerId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(412), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1900000.0,
                            SerialNumber = "SN-9BEE5B80",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(422), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2000000.0,
                            SerialNumber = "SN-2F490BE0",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ComputerId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(430), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 2100000.0,
                            SerialNumber = "SN-F77D9F9E",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ComputerId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(439), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 2200000.0,
                            SerialNumber = "SN-0BDEBC4E",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(450), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 2300000.0,
                            SerialNumber = "SN-AA68E10C",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ComputerId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(459), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 2400000.0,
                            SerialNumber = "SN-6710CDCD",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ComputerId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(467), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2500000.0,
                            SerialNumber = "SN-B79B5D3B",
                            Status = "Đang sử dụng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "EPU-PC-001",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9224), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 1",
                            PurchaseDate = new DateTime(2026, 3, 22, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9176),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "EPU-PC-002",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9233), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 2",
                            PurchaseDate = new DateTime(2026, 3, 12, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9232),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "EPU-PC-003",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9239), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 3",
                            PurchaseDate = new DateTime(2026, 3, 2, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9238),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "EPU-PC-004",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9246), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 4",
                            PurchaseDate = new DateTime(2026, 2, 20, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9245),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "EPU-PC-005",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9252), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 5",
                            PurchaseDate = new DateTime(2026, 2, 10, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9251),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "EPU-PC-006",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9260), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 6",
                            PurchaseDate = new DateTime(2026, 1, 31, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9259),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "EPU-PC-007",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9291), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 7",
                            PurchaseDate = new DateTime(2026, 1, 21, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9290),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "EPU-PC-008",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9308), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 8",
                            PurchaseDate = new DateTime(2026, 1, 11, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9307),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "EPU-PC-009",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9314), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 9",
                            PurchaseDate = new DateTime(2026, 1, 1, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9313),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "EPU-PC-010",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9323), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 11,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 10",
                            PurchaseDate = new DateTime(2025, 12, 22, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9322),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 11,
                            AssetCode = "EPU-PC-011",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9329), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 12,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 11",
                            PurchaseDate = new DateTime(2025, 12, 12, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9328),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 12,
                            AssetCode = "EPU-PC-012",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9335), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 13,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 12",
                            PurchaseDate = new DateTime(2025, 12, 2, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9334),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 13,
                            AssetCode = "EPU-PC-013",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9341), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 14,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 13",
                            PurchaseDate = new DateTime(2025, 11, 22, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9340),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 14,
                            AssetCode = "EPU-PC-014",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9346), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 15,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 14",
                            PurchaseDate = new DateTime(2025, 11, 12, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9345),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 15,
                            AssetCode = "EPU-PC-015",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9352), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 16,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 15",
                            PurchaseDate = new DateTime(2025, 11, 2, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9351),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 16,
                            AssetCode = "EPU-PC-016",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9360), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 17,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 16",
                            PurchaseDate = new DateTime(2025, 10, 23, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9358),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 17,
                            AssetCode = "EPU-PC-017",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9373), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 18,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 17",
                            PurchaseDate = new DateTime(2025, 10, 13, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9372),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 18,
                            AssetCode = "EPU-PC-018",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9384), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 19,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 18",
                            PurchaseDate = new DateTime(2025, 10, 3, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9382),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            AssetCode = "EPU-PC-019",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9394), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 20,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 19",
                            PurchaseDate = new DateTime(2025, 9, 23, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9393),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 20,
                            AssetCode = "EPU-PC-020",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(9402), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 20",
                            PurchaseDate = new DateTime(2025, 9, 13, 16, 6, 13, 807, DateTimeKind.Local).AddTicks(9401),
                            Status = "Đang dùng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8011), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà B",
                            Name = "Khoa CNTT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8064), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà C",
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8068), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà D",
                            Name = "Phòng Hành chính"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8072), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà A",
                            Name = "Phòng Kế hoạch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8075), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà B",
                            Name = "Trung tâm Thí nghiệm"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8081), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà C",
                            Name = "Khoa Điện"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8084), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà D",
                            Name = "Khoa Cơ khí"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8087), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà A",
                            Name = "Phòng Tài vụ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8090), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà B",
                            Name = "Thư viện"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8095), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà C",
                            Name = "Phòng Bảo vệ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8102), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà D",
                            Name = "Phòng chức năng 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8105), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà A",
                            Name = "Phòng chức năng 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8109), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà B",
                            Name = "Phòng chức năng 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8113), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà C",
                            Name = "Phòng chức năng 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8117), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà D",
                            Name = "Phòng chức năng 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8121), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà A",
                            Name = "Phòng chức năng 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8126), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà B",
                            Name = "Phòng chức năng 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8132), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà C",
                            Name = "Phòng chức năng 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8136), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà D",
                            Name = "Phòng chức năng 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 807, DateTimeKind.Unspecified).AddTicks(8146), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà A",
                            Name = "Phòng chức năng 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerId = 2,
                            Cost = 150000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(575), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 1",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 31, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(559)
                        },
                        new
                        {
                            Id = 2,
                            ComputerId = 3,
                            Cost = 200000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(588), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 2",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 30, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(585)
                        },
                        new
                        {
                            Id = 3,
                            ComputerId = 4,
                            Cost = 250000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(596), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 3",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 29, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(592)
                        },
                        new
                        {
                            Id = 4,
                            ComputerId = 5,
                            Cost = 300000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(601), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 4",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 28, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(598)
                        },
                        new
                        {
                            Id = 5,
                            ComputerId = 6,
                            Cost = 350000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(607), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 5",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 27, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(604)
                        },
                        new
                        {
                            Id = 6,
                            ComputerId = 7,
                            Cost = 400000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(615), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 6",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 26, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(612)
                        },
                        new
                        {
                            Id = 7,
                            ComputerId = 8,
                            Cost = 450000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1198), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 7",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 25, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(618)
                        },
                        new
                        {
                            Id = 8,
                            ComputerId = 9,
                            Cost = 500000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1203), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 8",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 24, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1200)
                        },
                        new
                        {
                            Id = 9,
                            ComputerId = 10,
                            Cost = 550000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1206), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 9",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 23, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1204)
                        },
                        new
                        {
                            Id = 10,
                            ComputerId = 11,
                            Cost = 600000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1213), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 10",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 22, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1210)
                        },
                        new
                        {
                            Id = 11,
                            ComputerId = 12,
                            Cost = 650000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1217), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 11",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 21, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1215)
                        },
                        new
                        {
                            Id = 12,
                            ComputerId = 13,
                            Cost = 700000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1221), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 12",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 20, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1219)
                        },
                        new
                        {
                            Id = 13,
                            ComputerId = 14,
                            Cost = 750000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1225), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 13",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 19, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1223)
                        },
                        new
                        {
                            Id = 14,
                            ComputerId = 15,
                            Cost = 800000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1229), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 14",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 18, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1227)
                        },
                        new
                        {
                            Id = 15,
                            ComputerId = 16,
                            Cost = 850000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1233), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 15",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 17, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1231)
                        },
                        new
                        {
                            Id = 16,
                            ComputerId = 17,
                            Cost = 900000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1237), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 16",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 16, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1235)
                        },
                        new
                        {
                            Id = 17,
                            ComputerId = 18,
                            Cost = 950000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1241), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 17",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 15, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1239)
                        },
                        new
                        {
                            Id = 18,
                            ComputerId = 19,
                            Cost = 1000000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1247), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 18",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 14, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1245)
                        },
                        new
                        {
                            Id = 19,
                            ComputerId = 20,
                            Cost = 1050000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1252), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 19",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 13, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1250)
                        },
                        new
                        {
                            Id = 20,
                            ComputerId = 1,
                            Cost = 1100000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 16, 6, 13, 808, DateTimeKind.Unspecified).AddTicks(1257), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 20",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 12, 16, 6, 13, 808, DateTimeKind.Local).AddTicks(1254)
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("Components")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Computers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Computers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
