// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyTaiSan.Data;

#nullable disable

namespace WebQuanLyTaiSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401080012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(102), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 1",
                            IsDeleted = false,
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(108), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 2",
                            IsDeleted = false,
                            Name = "Linh kiện rời"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(112), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 3",
                            IsDeleted = false,
                            Name = "Thiết bị mạng"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(114), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 4",
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(117), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 5",
                            IsDeleted = false,
                            Name = "Máy in"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(120), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 6",
                            IsDeleted = false,
                            Name = "Máy chiếu"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(122), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 7",
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(124), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 8",
                            IsDeleted = false,
                            Name = "Thiết bị lưu trữ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(128), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 9",
                            IsDeleted = false,
                            Name = "Thiết bị loại 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(132), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 10",
                            IsDeleted = false,
                            Name = "Thiết bị loại 10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(168), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 11",
                            IsDeleted = false,
                            Name = "Thiết bị loại 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(172), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 12",
                            IsDeleted = false,
                            Name = "Thiết bị loại 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(175), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 13",
                            IsDeleted = false,
                            Name = "Thiết bị loại 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(177), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 14",
                            IsDeleted = false,
                            Name = "Thiết bị loại 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(179), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 15",
                            IsDeleted = false,
                            Name = "Thiết bị loại 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(182), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 16",
                            IsDeleted = false,
                            Name = "Thiết bị loại 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(184), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 17",
                            IsDeleted = false,
                            Name = "Thiết bị loại 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(189), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 18",
                            IsDeleted = false,
                            Name = "Thiết bị loại 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(192), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 19",
                            IsDeleted = false,
                            Name = "Thiết bị loại 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(195), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 20",
                            IsDeleted = false,
                            Name = "Thiết bị loại 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ComputerId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(605), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 600000.0,
                            SerialNumber = "SN-5FB53F7E",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ComputerId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(614), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 700000.0,
                            SerialNumber = "SN-6031CF50",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(619), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 800000.0,
                            SerialNumber = "SN-939E9E19",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ComputerId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(624), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 900000.0,
                            SerialNumber = "SN-99AEC86A",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ComputerId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(629), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1000000.0,
                            SerialNumber = "SN-32361A6F",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(634), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1100000.0,
                            SerialNumber = "SN-C9AB4CC1",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ComputerId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(638), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1200000.0,
                            SerialNumber = "SN-391D0AF4",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ComputerId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(656), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1300000.0,
                            SerialNumber = "SN-7662EC6B",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(660), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1400000.0,
                            SerialNumber = "SN-BFE7A507",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ComputerId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(666), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1500000.0,
                            SerialNumber = "SN-4EA2168A",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ComputerId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(671), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1600000.0,
                            SerialNumber = "SN-5DC54975",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(675), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1700000.0,
                            SerialNumber = "SN-68F0AF2F",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ComputerId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(745), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1800000.0,
                            SerialNumber = "SN-803AF167",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ComputerId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(749), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1900000.0,
                            SerialNumber = "SN-C1D206E0",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(753), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2000000.0,
                            SerialNumber = "SN-23C3FBC9",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ComputerId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(761), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 2100000.0,
                            SerialNumber = "SN-AB072D8C",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ComputerId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(765), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 2200000.0,
                            SerialNumber = "SN-6FD1D701",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 2300000.0,
                            SerialNumber = "SN-B02DCBD6",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ComputerId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(775), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 2400000.0,
                            SerialNumber = "SN-6CC79410",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ComputerId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(779), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2500000.0,
                            SerialNumber = "SN-2DAB79F4",
                            Status = "Đang sử dụng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "EPU-PC-001",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(290), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 1",
                            PurchaseDate = new DateTime(2026, 3, 22, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(280),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "EPU-PC-002",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(298), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 2",
                            PurchaseDate = new DateTime(2026, 3, 12, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(297),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "EPU-PC-003",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(302), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 3",
                            PurchaseDate = new DateTime(2026, 3, 2, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(302),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "EPU-PC-004",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(307), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 4",
                            PurchaseDate = new DateTime(2026, 2, 20, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(306),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "EPU-PC-005",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(311), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 5",
                            PurchaseDate = new DateTime(2026, 2, 10, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(311),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "EPU-PC-006",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(317), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 6",
                            PurchaseDate = new DateTime(2026, 1, 31, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(316),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "EPU-PC-007",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(321), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 7",
                            PurchaseDate = new DateTime(2026, 1, 21, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(321),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "EPU-PC-008",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(342), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 8",
                            PurchaseDate = new DateTime(2026, 1, 11, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(341),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "EPU-PC-009",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(346), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 9",
                            PurchaseDate = new DateTime(2026, 1, 1, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(346),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "EPU-PC-010",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(353), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 11,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 10",
                            PurchaseDate = new DateTime(2025, 12, 22, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(352),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 11,
                            AssetCode = "EPU-PC-011",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(358), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 12,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 11",
                            PurchaseDate = new DateTime(2025, 12, 12, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(357),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 12,
                            AssetCode = "EPU-PC-012",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(362), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 13,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 12",
                            PurchaseDate = new DateTime(2025, 12, 2, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(361),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 13,
                            AssetCode = "EPU-PC-013",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(367), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 14,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 13",
                            PurchaseDate = new DateTime(2025, 11, 22, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(366),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 14,
                            AssetCode = "EPU-PC-014",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(371), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 15,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 14",
                            PurchaseDate = new DateTime(2025, 11, 12, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(370),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 15,
                            AssetCode = "EPU-PC-015",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(396), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 16,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 15",
                            PurchaseDate = new DateTime(2025, 11, 2, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(396),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 16,
                            AssetCode = "EPU-PC-016",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(401), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 17,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 16",
                            PurchaseDate = new DateTime(2025, 10, 23, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(400),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 17,
                            AssetCode = "EPU-PC-017",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(406), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 18,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 17",
                            PurchaseDate = new DateTime(2025, 10, 13, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(405),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 18,
                            AssetCode = "EPU-PC-018",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(412), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 19,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 18",
                            PurchaseDate = new DateTime(2025, 10, 3, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(411),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            AssetCode = "EPU-PC-019",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(416), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 20,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 19",
                            PurchaseDate = new DateTime(2025, 9, 23, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(415),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 20,
                            AssetCode = "EPU-PC-020",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(421), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 20",
                            PurchaseDate = new DateTime(2025, 9, 13, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(420),
                            Status = "Đang dùng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9758), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà B",
                            Name = "Khoa CNTT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9807), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà C",
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9810), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà D",
                            Name = "Phòng Hành chính"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9812), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà A",
                            Name = "Phòng Kế hoạch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9853), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà B",
                            Name = "Trung tâm Thí nghiệm"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9858), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà C",
                            Name = "Khoa Điện"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9861), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà D",
                            Name = "Khoa Cơ khí"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9864), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà A",
                            Name = "Phòng Tài vụ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9866), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà B",
                            Name = "Thư viện"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9870), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà C",
                            Name = "Phòng Bảo vệ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9876), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà D",
                            Name = "Phòng chức năng 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9880), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà A",
                            Name = "Phòng chức năng 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9883), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà B",
                            Name = "Phòng chức năng 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9886), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà C",
                            Name = "Phòng chức năng 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9889), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà D",
                            Name = "Phòng chức năng 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9891), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà A",
                            Name = "Phòng chức năng 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9894), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà B",
                            Name = "Phòng chức năng 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9899), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà C",
                            Name = "Phòng chức năng 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9902), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà D",
                            Name = "Phòng chức năng 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 234, DateTimeKind.Unspecified).AddTicks(9905), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà A",
                            Name = "Phòng chức năng 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerId = 2,
                            Cost = 150000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(838), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 1",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 31, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(831)
                        },
                        new
                        {
                            Id = 2,
                            ComputerId = 3,
                            Cost = 200000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(844), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 2",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 30, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(842)
                        },
                        new
                        {
                            Id = 3,
                            ComputerId = 4,
                            Cost = 250000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(848), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 3",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 29, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(846)
                        },
                        new
                        {
                            Id = 4,
                            ComputerId = 5,
                            Cost = 300000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(851), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 4",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 28, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(849)
                        },
                        new
                        {
                            Id = 5,
                            ComputerId = 6,
                            Cost = 350000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(854), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 5",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 27, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(852)
                        },
                        new
                        {
                            Id = 6,
                            ComputerId = 7,
                            Cost = 400000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(858), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 6",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 26, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(856)
                        },
                        new
                        {
                            Id = 7,
                            ComputerId = 8,
                            Cost = 450000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(861), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 7",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 25, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(860)
                        },
                        new
                        {
                            Id = 8,
                            ComputerId = 9,
                            Cost = 500000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(864), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 8",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 24, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(862)
                        },
                        new
                        {
                            Id = 9,
                            ComputerId = 10,
                            Cost = 550000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(867), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 9",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 23, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(865)
                        },
                        new
                        {
                            Id = 10,
                            ComputerId = 11,
                            Cost = 600000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(871), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 10",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 22, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            Id = 11,
                            ComputerId = 12,
                            Cost = 650000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(875), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 11",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 21, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(873)
                        },
                        new
                        {
                            Id = 12,
                            ComputerId = 13,
                            Cost = 700000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(878), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 12",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 20, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(876)
                        },
                        new
                        {
                            Id = 13,
                            ComputerId = 14,
                            Cost = 750000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(881), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 13",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 19, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(879)
                        },
                        new
                        {
                            Id = 14,
                            ComputerId = 15,
                            Cost = 800000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(884), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 14",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 18, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(883)
                        },
                        new
                        {
                            Id = 15,
                            ComputerId = 16,
                            Cost = 850000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(888), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 15",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 17, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(886)
                        },
                        new
                        {
                            Id = 16,
                            ComputerId = 17,
                            Cost = 900000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(891), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 16",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 16, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(890)
                        },
                        new
                        {
                            Id = 17,
                            ComputerId = 18,
                            Cost = 950000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(895), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 17",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 15, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(893)
                        },
                        new
                        {
                            Id = 18,
                            ComputerId = 19,
                            Cost = 1000000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(960), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 18",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 14, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(957)
                        },
                        new
                        {
                            Id = 19,
                            ComputerId = 20,
                            Cost = 1050000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(963), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 19",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 13, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(962)
                        },
                        new
                        {
                            Id = 20,
                            ComputerId = 1,
                            Cost = 1100000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 15, 0, 11, 235, DateTimeKind.Unspecified).AddTicks(967), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 20",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 12, 15, 0, 11, 235, DateTimeKind.Local).AddTicks(965)
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("Components")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Computers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Computers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
