// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyTaiSan.Data;

#nullable disable

namespace WebQuanLyTaiSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409051545_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3072), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 1",
                            IsDeleted = false,
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3077), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 2",
                            IsDeleted = false,
                            Name = "Linh kiện rời"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3079), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 3",
                            IsDeleted = false,
                            Name = "Thiết bị mạng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3081), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 4",
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3083), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 5",
                            IsDeleted = false,
                            Name = "Máy in"
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3086), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 6",
                            IsDeleted = false,
                            Name = "Máy chiếu"
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3089), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 7",
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3091), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 8",
                            IsDeleted = false,
                            Name = "Thiết bị lưu trữ"
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3094), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 9",
                            IsDeleted = false,
                            Name = "Thiết bị loại 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3098), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 10",
                            IsDeleted = false,
                            Name = "Thiết bị loại 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3102), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 11",
                            IsDeleted = false,
                            Name = "Thiết bị loại 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3104), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 12",
                            IsDeleted = false,
                            Name = "Thiết bị loại 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3107), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 13",
                            IsDeleted = false,
                            Name = "Thiết bị loại 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3110), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 14",
                            IsDeleted = false,
                            Name = "Thiết bị loại 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3113), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 15",
                            IsDeleted = false,
                            Name = "Thiết bị loại 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3115), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 16",
                            IsDeleted = false,
                            Name = "Thiết bị loại 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3118), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 17",
                            IsDeleted = false,
                            Name = "Thiết bị loại 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3122), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 18",
                            IsDeleted = false,
                            Name = "Thiết bị loại 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3124), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 19",
                            IsDeleted = false,
                            Name = "Thiết bị loại 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3127), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 20",
                            IsDeleted = false,
                            Name = "Thiết bị loại 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ComputerId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3541), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 600000.0,
                            SerialNumber = "SN-703E0F69",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ComputerId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3547), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 700000.0,
                            SerialNumber = "SN-863F97B6",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3583), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 800000.0,
                            SerialNumber = "SN-8E6E491A",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ComputerId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3587), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 900000.0,
                            SerialNumber = "SN-2BE3723B",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ComputerId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3591), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1000000.0,
                            SerialNumber = "SN-12A2B4B5",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3597), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1100000.0,
                            SerialNumber = "SN-1053F970",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ComputerId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3614), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1200000.0,
                            SerialNumber = "SN-4855BF4F",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ComputerId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3618), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1300000.0,
                            SerialNumber = "SN-AFF9BB4E",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3622), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1400000.0,
                            SerialNumber = "SN-D7628F9D",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ComputerId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3627), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1500000.0,
                            SerialNumber = "SN-55950A14",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ComputerId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3631), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1600000.0,
                            SerialNumber = "SN-ADA3A3CE",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3634), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1700000.0,
                            SerialNumber = "SN-5AE453F9",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ComputerId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3638), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1800000.0,
                            SerialNumber = "SN-180D197C",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ComputerId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3642), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1900000.0,
                            SerialNumber = "SN-211EBD86",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3649), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2000000.0,
                            SerialNumber = "SN-9B3E867A",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ComputerId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3653), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 2100000.0,
                            SerialNumber = "SN-43FCB1E5",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ComputerId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3657), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 2200000.0,
                            SerialNumber = "SN-60ACF3CD",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3662), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 2300000.0,
                            SerialNumber = "SN-2E83835C",
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ComputerId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3665), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 2400000.0,
                            SerialNumber = "SN-F447C8B2",
                            Status = "Đang sử dụng"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ComputerId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3669), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2500000.0,
                            SerialNumber = "SN-0E9D8D03",
                            Status = "Đang sử dụng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "EPU-PC-001",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3246), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 1",
                            PurchaseDate = new DateTime(2026, 3, 30, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3237),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "EPU-PC-002",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3253), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 2",
                            PurchaseDate = new DateTime(2026, 3, 20, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3252),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "EPU-PC-003",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3257), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 3",
                            PurchaseDate = new DateTime(2026, 3, 10, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3256),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "EPU-PC-004",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3261), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 4",
                            PurchaseDate = new DateTime(2026, 2, 28, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3261),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "EPU-PC-005",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3266), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 5",
                            PurchaseDate = new DateTime(2026, 2, 18, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3265),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "EPU-PC-006",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3271), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 6",
                            PurchaseDate = new DateTime(2026, 2, 8, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3270),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "EPU-PC-007",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3275), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 7",
                            PurchaseDate = new DateTime(2026, 1, 29, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3275),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "EPU-PC-008",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3285), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 8",
                            PurchaseDate = new DateTime(2026, 1, 19, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3285),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "EPU-PC-009",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3290), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 9",
                            PurchaseDate = new DateTime(2026, 1, 9, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3289),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "EPU-PC-010",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3296), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 11,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 10",
                            PurchaseDate = new DateTime(2025, 12, 30, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3295),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 11,
                            AssetCode = "EPU-PC-011",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3300), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 12,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 11",
                            PurchaseDate = new DateTime(2025, 12, 20, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3299),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 12,
                            AssetCode = "EPU-PC-012",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3304), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 13,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 12",
                            PurchaseDate = new DateTime(2025, 12, 10, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3304),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 13,
                            AssetCode = "EPU-PC-013",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3309), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 14,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 13",
                            PurchaseDate = new DateTime(2025, 11, 30, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3308),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 14,
                            AssetCode = "EPU-PC-014",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3313), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 15,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 14",
                            PurchaseDate = new DateTime(2025, 11, 20, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3313),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 15,
                            AssetCode = "EPU-PC-015",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3318), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 16,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 15",
                            PurchaseDate = new DateTime(2025, 11, 10, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3317),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 16,
                            AssetCode = "EPU-PC-016",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3322), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 17,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 16",
                            PurchaseDate = new DateTime(2025, 10, 31, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3321),
                            Status = "Đang dùng"
                        },
                        new
                        {
                            Id = 17,
                            AssetCode = "EPU-PC-017",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3326), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 18,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 17",
                            PurchaseDate = new DateTime(2025, 10, 21, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3326),
                            Status = "Bảo trì"
                        },
                        new
                        {
                            Id = 18,
                            AssetCode = "EPU-PC-018",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3331), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 19,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 18",
                            PurchaseDate = new DateTime(2025, 10, 11, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3330),
                            Status = "Trong kho"
                        },
                        new
                        {
                            Id = 19,
                            AssetCode = "EPU-PC-019",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3335), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 20,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 19",
                            PurchaseDate = new DateTime(2025, 10, 1, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3335),
                            Status = "Hỏng"
                        },
                        new
                        {
                            Id = 20,
                            AssetCode = "EPU-PC-020",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3340), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 20",
                            PurchaseDate = new DateTime(2025, 9, 21, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3339),
                            Status = "Đang dùng"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2766), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà B",
                            Name = "Khoa CNTT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2805), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà C",
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2809), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà D",
                            Name = "Phòng Hành chính"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2811), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà A",
                            Name = "Phòng Kế hoạch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2819), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà B",
                            Name = "Trung tâm Thí nghiệm"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2823), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà C",
                            Name = "Khoa Điện"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2826), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà D",
                            Name = "Khoa Cơ khí"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2828), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà A",
                            Name = "Phòng Tài vụ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2830), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà B",
                            Name = "Thư viện"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2834), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà C",
                            Name = "Phòng Bảo vệ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2839), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà D",
                            Name = "Phòng chức năng 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2842), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà A",
                            Name = "Phòng chức năng 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2846), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà B",
                            Name = "Phòng chức năng 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2849), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà C",
                            Name = "Phòng chức năng 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2852), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà D",
                            Name = "Phòng chức năng 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2855), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà A",
                            Name = "Phòng chức năng 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2859), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà B",
                            Name = "Phòng chức năng 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2896), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà C",
                            Name = "Phòng chức năng 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2899), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà D",
                            Name = "Phòng chức năng 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(2902), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà A",
                            Name = "Phòng chức năng 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerId = 2,
                            Cost = 150000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3789), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 1",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 8, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3782)
                        },
                        new
                        {
                            Id = 2,
                            ComputerId = 3,
                            Cost = 200000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3795), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 2",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 7, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3792)
                        },
                        new
                        {
                            Id = 3,
                            ComputerId = 4,
                            Cost = 250000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3798), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 3",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 6, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3796)
                        },
                        new
                        {
                            Id = 4,
                            ComputerId = 5,
                            Cost = 300000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3801), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 4",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 5, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3800)
                        },
                        new
                        {
                            Id = 5,
                            ComputerId = 6,
                            Cost = 350000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3804), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 5",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 4, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3803)
                        },
                        new
                        {
                            Id = 6,
                            ComputerId = 7,
                            Cost = 400000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3808), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 6",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 3, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3807)
                        },
                        new
                        {
                            Id = 7,
                            ComputerId = 8,
                            Cost = 450000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3811), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 7",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 2, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3810)
                        },
                        new
                        {
                            Id = 8,
                            ComputerId = 9,
                            Cost = 500000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3814), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 8",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 1, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3812)
                        },
                        new
                        {
                            Id = 9,
                            ComputerId = 10,
                            Cost = 550000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3817), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 9",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 31, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3815)
                        },
                        new
                        {
                            Id = 10,
                            ComputerId = 11,
                            Cost = 600000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3821), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 10",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 30, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3819)
                        },
                        new
                        {
                            Id = 11,
                            ComputerId = 12,
                            Cost = 650000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3825), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 11",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 29, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3823)
                        },
                        new
                        {
                            Id = 12,
                            ComputerId = 13,
                            Cost = 700000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3827), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 12",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 28, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3826)
                        },
                        new
                        {
                            Id = 13,
                            ComputerId = 14,
                            Cost = 750000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3830), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 13",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 27, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3829)
                        },
                        new
                        {
                            Id = 14,
                            ComputerId = 15,
                            Cost = 800000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3833), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 14",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 26, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3832)
                        },
                        new
                        {
                            Id = 15,
                            ComputerId = 16,
                            Cost = 850000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3836), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 15",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 25, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3835)
                        },
                        new
                        {
                            Id = 16,
                            ComputerId = 17,
                            Cost = 900000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3839), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 16",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 24, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3838)
                        },
                        new
                        {
                            Id = 17,
                            ComputerId = 18,
                            Cost = 950000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3842), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 17",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 23, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3840)
                        },
                        new
                        {
                            Id = 18,
                            ComputerId = 19,
                            Cost = 1000000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3846), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 18",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 22, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3844)
                        },
                        new
                        {
                            Id = 19,
                            ComputerId = 20,
                            Cost = 1050000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3849), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 19",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 21, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3847)
                        },
                        new
                        {
                            Id = 20,
                            ComputerId = 1,
                            Cost = 1100000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 15, 41, 312, DateTimeKind.Unspecified).AddTicks(3852), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 20",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 20, 12, 15, 41, 312, DateTimeKind.Local).AddTicks(3850)
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("Components")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Computers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Computers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
