// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyTaiSan.Data;

#nullable disable

namespace WebQuanLyTaiSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418145031_AddPackagingAndAccessoriesToComputer")]
    partial class AddPackagingAndAccessoriesToComputer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2414), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 1",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2420), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 2",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Linh kiện rời"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2425), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 3",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị mạng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2430), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 4",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2435), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 5",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy in"
                        },
                        new
                        {
                            Id = 6,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2440), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 6",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy chiếu"
                        },
                        new
                        {
                            Id = 7,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2445), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 7",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 8,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2450), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 8",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị lưu trữ"
                        },
                        new
                        {
                            Id = 9,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2457), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 9",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2464), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 10",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2471), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 11",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2476), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 12",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2482), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 13",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2496), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 14",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2503), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 15",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2509), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 16",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2515), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 17",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2522), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 18",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2528), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 19",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2534), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 20",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ComputerId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3357), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 600000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3179),
                            SerialNumber = "SN-F3753DC5",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ComputerId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3405), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 700000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3398),
                            SerialNumber = "SN-B2AC32E9",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3413), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 800000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3407),
                            SerialNumber = "SN-5D919F72",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ComputerId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3420), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 900000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3414),
                            SerialNumber = "SN-C0BDB822",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ComputerId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3428), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1000000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3422),
                            SerialNumber = "SN-C6B7DA98",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3436), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1100000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3430),
                            SerialNumber = "SN-BDB266EA",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ComputerId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3465), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1200000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3437),
                            SerialNumber = "SN-B2B2417D",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ComputerId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3473), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1300000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3467),
                            SerialNumber = "SN-A54CFBF5",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3480), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1400000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3474),
                            SerialNumber = "SN-8D5F2A77",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ComputerId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3522), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1500000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3482),
                            SerialNumber = "SN-7C83A5E5",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ComputerId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3530), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1600000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3524),
                            SerialNumber = "SN-2BB2A8E4",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3536), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1700000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3531),
                            SerialNumber = "SN-1E2D648D",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ComputerId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3545), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1800000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3538),
                            SerialNumber = "SN-5005085C",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ComputerId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3551), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1900000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3546),
                            SerialNumber = "SN-5C5D9DE2",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3573), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2000000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3553),
                            SerialNumber = "SN-DDDAC877",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ComputerId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3580), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 2100000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3574),
                            SerialNumber = "SN-1E1D34E9",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ComputerId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3586), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 2200000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3581),
                            SerialNumber = "SN-FEF3C531",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3594), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 2300000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3589),
                            SerialNumber = "SN-C762A1AA",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ComputerId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3643), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 2400000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3596),
                            SerialNumber = "SN-81A54138",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ComputerId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3651), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2500000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3645),
                            SerialNumber = "SN-45A9A8F9",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accessories")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Packaging")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "EPU-PC-001",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2735), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            EmployeeId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 1",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 4, 8, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2717),
                            PurchasePrice = 10500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "EPU-PC-002",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2747), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            EmployeeId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 2",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 29, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2746),
                            PurchasePrice = 11000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "EPU-PC-003",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2756), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            EmployeeId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 3",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 19, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2755),
                            PurchasePrice = 11500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "EPU-PC-004",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2765), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            EmployeeId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 4",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 9, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2764),
                            PurchasePrice = 12000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "EPU-PC-005",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2774), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            EmployeeId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 5",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 27, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2773),
                            PurchasePrice = 12500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "EPU-PC-006",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2785), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            EmployeeId = 7,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 6",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 17, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2783),
                            PurchasePrice = 13000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "EPU-PC-007",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2794), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            EmployeeId = 8,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 7",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 7, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2793),
                            PurchasePrice = 13500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "EPU-PC-008",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2926), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            EmployeeId = 9,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 8",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 28, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2917),
                            PurchasePrice = 14000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "EPU-PC-009",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2935), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            EmployeeId = 10,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 9",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 18, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2934),
                            PurchasePrice = 14500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "EPU-PC-010",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2948), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 11,
                            EmployeeId = 11,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 10",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 8, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2946),
                            PurchasePrice = 15000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 11,
                            AssetCode = "EPU-PC-011",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2958), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 12,
                            EmployeeId = 12,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 11",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 29, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2956),
                            PurchasePrice = 15500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 12,
                            AssetCode = "EPU-PC-012",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2968), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 13,
                            EmployeeId = 13,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 12",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 19, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2966),
                            PurchasePrice = 16000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 13,
                            AssetCode = "EPU-PC-013",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2977), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 14,
                            EmployeeId = 14,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 13",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 9, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2976),
                            PurchasePrice = 16500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 14,
                            AssetCode = "EPU-PC-014",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2991), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 15,
                            EmployeeId = 15,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 14",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 29, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(2990),
                            PurchasePrice = 17000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 15,
                            AssetCode = "EPU-PC-015",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3042), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 16,
                            EmployeeId = 1,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 15",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 19, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3020),
                            PurchasePrice = 17500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 16,
                            AssetCode = "EPU-PC-016",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3052), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 17,
                            EmployeeId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 16",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 9, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3051),
                            PurchasePrice = 18000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 17,
                            AssetCode = "EPU-PC-017",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3062), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 18,
                            EmployeeId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 17",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 30, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3061),
                            PurchasePrice = 18500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 18,
                            AssetCode = "EPU-PC-018",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3072), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 19,
                            EmployeeId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 18",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 20, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3071),
                            PurchasePrice = 19000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 19,
                            AssetCode = "EPU-PC-019",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3081), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 20,
                            EmployeeId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 19",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 10, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3080),
                            PurchasePrice = 19500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 20,
                            AssetCode = "EPU-PC-020",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3091), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            EmployeeId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 20",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 9, 30, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3089),
                            PurchasePrice = 20000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(903), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "CNTT",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà B",
                            Name = "Khoa CNTT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1195), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DT",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà C",
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1206), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "HC",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà D",
                            Name = "Phòng Hành chính"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1212), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "KH",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà A",
                            Name = "Phòng Kế hoạch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1220), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TTTN",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà B",
                            Name = "Trung tâm Thí nghiệm"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1237), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DIEN",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà C",
                            Name = "Khoa Điện"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1245), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "CK",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà D",
                            Name = "Khoa Cơ khí"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1252), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TVU",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà A",
                            Name = "Phòng Tài vụ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1258), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TV",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà B",
                            Name = "Thư viện"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1267), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "BV",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà C",
                            Name = "Phòng Bảo vệ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1281), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT11",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà D",
                            Name = "Phòng chức năng 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1291), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT12",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà A",
                            Name = "Phòng chức năng 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1312), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT13",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà B",
                            Name = "Phòng chức năng 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1325), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT14",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà C",
                            Name = "Phòng chức năng 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1396), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT15",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà D",
                            Name = "Phòng chức năng 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1427), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT16",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà A",
                            Name = "Phòng chức năng 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1494), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT17",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà B",
                            Name = "Phòng chức năng 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1506), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT18",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà C",
                            Name = "Phòng chức năng 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1517), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT19",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà D",
                            Name = "Phòng chức năng 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(1528), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT20",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà A",
                            Name = "Phòng chức năng 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2150), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            Email = "nv1@epu.edu.vn",
                            EmployeeCode = "NV001",
                            FullName = "Nhân viên 1",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2164), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            Email = "nv2@epu.edu.vn",
                            EmployeeCode = "NV002",
                            FullName = "Nhân viên 2",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2178), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            Email = "nv3@epu.edu.vn",
                            EmployeeCode = "NV003",
                            FullName = "Nhân viên 3",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2186), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            Email = "nv4@epu.edu.vn",
                            EmployeeCode = "NV004",
                            FullName = "Nhân viên 4",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2194), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            Email = "nv5@epu.edu.vn",
                            EmployeeCode = "NV005",
                            FullName = "Nhân viên 5",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2204), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            Email = "nv6@epu.edu.vn",
                            EmployeeCode = "NV006",
                            FullName = "Nhân viên 6",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2212), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            Email = "nv7@epu.edu.vn",
                            EmployeeCode = "NV007",
                            FullName = "Nhân viên 7",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2219), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            Email = "nv8@epu.edu.vn",
                            EmployeeCode = "NV008",
                            FullName = "Nhân viên 8",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2226), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            Email = "nv9@epu.edu.vn",
                            EmployeeCode = "NV009",
                            FullName = "Nhân viên 9",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2237), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            Email = "nv10@epu.edu.vn",
                            EmployeeCode = "NV010",
                            FullName = "Nhân viên 10",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2245), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            Email = "nv11@epu.edu.vn",
                            EmployeeCode = "NV011",
                            FullName = "Nhân viên 11",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2263), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            Email = "nv12@epu.edu.vn",
                            EmployeeCode = "NV012",
                            FullName = "Nhân viên 12",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2271), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            Email = "nv13@epu.edu.vn",
                            EmployeeCode = "NV013",
                            FullName = "Nhân viên 13",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2278), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            Email = "nv14@epu.edu.vn",
                            EmployeeCode = "NV014",
                            FullName = "Nhân viên 14",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(2285), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            Email = "nv15@epu.edu.vn",
                            EmployeeCode = "NV015",
                            FullName = "Nhân viên 15",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerId = 2,
                            Cost = 150000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3731), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 1",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 17, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3723),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 2,
                            ComputerId = 3,
                            Cost = 200000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3739), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 2",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 16, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3736),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 3,
                            ComputerId = 4,
                            Cost = 250000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3745), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 3",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 15, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3742),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 4,
                            ComputerId = 5,
                            Cost = 300000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3751), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 4",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 14, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3748),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 5,
                            ComputerId = 6,
                            Cost = 350000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3757), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 5",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 13, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3755),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 6,
                            ComputerId = 7,
                            Cost = 400000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3764), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 6",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 12, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3761),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 7,
                            ComputerId = 8,
                            Cost = 450000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3769), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 7",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 11, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3767),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 8,
                            ComputerId = 9,
                            Cost = 500000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3775), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 8",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 10, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3773),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 9,
                            ComputerId = 10,
                            Cost = 550000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3781), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 9",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 9, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3778),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 10,
                            ComputerId = 11,
                            Cost = 600000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3798), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 10",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 8, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3785),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 11,
                            ComputerId = 12,
                            Cost = 650000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3804), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 11",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 7, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3801),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 12,
                            ComputerId = 13,
                            Cost = 700000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3810), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 12",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 6, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3807),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 13,
                            ComputerId = 14,
                            Cost = 750000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3816), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 13",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 5, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3813),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 14,
                            ComputerId = 15,
                            Cost = 800000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3821), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 14",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 4, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3819),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 15,
                            ComputerId = 16,
                            Cost = 850000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3827), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 15",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 3, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3825),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 16,
                            ComputerId = 17,
                            Cost = 900000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3833), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 16",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 2, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3831),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 17,
                            ComputerId = 18,
                            Cost = 950000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3839), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 17",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 1, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3837),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 18,
                            ComputerId = 19,
                            Cost = 1000000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3846), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 18",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 31, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3843),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 19,
                            ComputerId = 20,
                            Cost = 1050000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3851), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 19",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 30, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3849),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 20,
                            ComputerId = 1,
                            Cost = 1100000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 965, DateTimeKind.Unspecified).AddTicks(3857), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 20",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 29, 21, 50, 29, 965, DateTimeKind.Local).AddTicks(3855),
                            Status = "Hoàn thành"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 21, 50, 29, 964, DateTimeKind.Unspecified).AddTicks(9854), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "admin@epu.edu.vn",
                            FullName = "Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "$2a$11$nY/tlMYDnLvW3K70H4ZtguiC75r5Oqlp0lfR5W3arrW9RyqwlmMy.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("Components")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Computers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Computers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("WebQuanLyTaiSan.Models.Employee", "Employee")
                        .WithMany("Computers")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Navigation("Computers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
