// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyTaiSan.Data;

#nullable disable

namespace WebQuanLyTaiSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418043608_InitialProDB")]
    partial class InitialProDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6226), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 1",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6233), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 2",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Linh kiện rời"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6238), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 3",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị mạng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6243), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 4",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6248), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 5",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy in"
                        },
                        new
                        {
                            Id = 6,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6261), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 6",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Máy chiếu"
                        },
                        new
                        {
                            Id = 7,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6266), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 7",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 8,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6272), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 8",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị lưu trữ"
                        },
                        new
                        {
                            Id = 9,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6279), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 9",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6288), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 10",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6295), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 11",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6302), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 12",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6309), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 13",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6316), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 14",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6322), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 15",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6329), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 16",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6336), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 17",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6342), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 18",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6349), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 19",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryCode = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6356), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Mô tả cho danh mục 20",
                            Group = 0,
                            IsDeleted = false,
                            Name = "Thiết bị loại 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ComputerId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7031), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 600000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6851),
                            SerialNumber = "SN-C65969F0",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ComputerId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7040), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 700000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7034),
                            SerialNumber = "SN-6BA34F51",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7047), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 800000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7041),
                            SerialNumber = "SN-D30F036F",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ComputerId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7054), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 900000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7048),
                            SerialNumber = "SN-B6FADB4C",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ComputerId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7061), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1000000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7055),
                            SerialNumber = "SN-7B308E3B",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7076), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1100000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7063),
                            SerialNumber = "SN-5DD7D60E",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ComputerId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7083), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1200000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7077),
                            SerialNumber = "SN-42CC93E6",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ComputerId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7107), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1300000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7085),
                            SerialNumber = "SN-1216987A",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7117), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1400000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7108),
                            SerialNumber = "SN-74901126",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ComputerId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7140), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 1500000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7119),
                            SerialNumber = "SN-6A25268C",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ComputerId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7153), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 1600000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7142),
                            SerialNumber = "SN-7692865D",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7160), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 1700000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7154),
                            SerialNumber = "SN-BB779E5F",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ComputerId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7168), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 1800000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7162),
                            SerialNumber = "SN-1758DEB5",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ComputerId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7175), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 1900000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7169),
                            SerialNumber = "SN-291BE856",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7187), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2000000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7176),
                            SerialNumber = "SN-DC37ED2B",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ComputerId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7194), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SSD Samsung 256GB",
                            Price = 2100000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7189),
                            SerialNumber = "SN-B9145DD2",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ComputerId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7204), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "CPU Intel i5",
                            Price = 2200000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7196),
                            SerialNumber = "SN-3DAAE00B",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7211), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "VGA GTX 1650",
                            Price = 2300000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7206),
                            SerialNumber = "SN-27A03514",
                            Status = "Trong kho",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ComputerId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7218), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Nguồn Cooler Master",
                            Price = 2400000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7213),
                            SerialNumber = "SN-1DFE57FA",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ComputerId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7225), new TimeSpan(0, 7, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "RAM Kington 8GB",
                            Price = 2500000.0,
                            PurchaseDate = new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7220),
                            SerialNumber = "SN-8E009254",
                            Status = "Đang sử dụng",
                            WarrantyMonths = 0
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accessories")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Packaging")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "EPU-PC-001",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6577), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            EmployeeId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 1",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 4, 8, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6563),
                            PurchasePrice = 10500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "EPU-PC-002",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6587), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            EmployeeId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 2",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 29, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6586),
                            PurchasePrice = 11000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "EPU-PC-003",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6595), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            EmployeeId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 3",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 19, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6594),
                            PurchasePrice = 11500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "EPU-PC-004",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6603), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            EmployeeId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 4",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 3, 9, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6602),
                            PurchasePrice = 12000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "EPU-PC-005",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6610), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            EmployeeId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 5",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 27, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6609),
                            PurchasePrice = 12500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "EPU-PC-006",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6618), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            EmployeeId = 7,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 6",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 17, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6617),
                            PurchasePrice = 13000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "EPU-PC-007",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6627), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            EmployeeId = 8,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 7",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 2, 7, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6626),
                            PurchasePrice = 13500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "EPU-PC-008",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6636), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            EmployeeId = 9,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 8",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 28, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6635),
                            PurchasePrice = 14000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "EPU-PC-009",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6645), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            EmployeeId = 10,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 9",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 18, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6644),
                            PurchasePrice = 14500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "EPU-PC-010",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6654), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 11,
                            EmployeeId = 11,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 10",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2026, 1, 8, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6653),
                            PurchasePrice = 15000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 11,
                            AssetCode = "EPU-PC-011",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6662), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 12,
                            EmployeeId = 12,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 11",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 29, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6661),
                            PurchasePrice = 15500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 12,
                            AssetCode = "EPU-PC-012",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6671), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 13,
                            EmployeeId = 13,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 12",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 19, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6670),
                            PurchasePrice = 16000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 13,
                            AssetCode = "EPU-PC-013",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6679), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 14,
                            EmployeeId = 14,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 13",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 12, 9, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6678),
                            PurchasePrice = 16500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 14,
                            AssetCode = "EPU-PC-014",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6698), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 15,
                            EmployeeId = 15,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 14",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 29, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6697),
                            PurchasePrice = 17000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 15,
                            AssetCode = "EPU-PC-015",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6730), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 16,
                            EmployeeId = 1,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 15",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 19, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6721),
                            PurchasePrice = 17500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 16,
                            AssetCode = "EPU-PC-016",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6747), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 17,
                            EmployeeId = 2,
                            IsDeleted = false,
                            Name = "HP ProDesk Gen 16",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 11, 9, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6746),
                            PurchasePrice = 18000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 17,
                            AssetCode = "EPU-PC-017",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6756), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 18,
                            EmployeeId = 3,
                            IsDeleted = false,
                            Name = "Lenovo ThinkCentre Gen 17",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 30, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6755),
                            PurchasePrice = 18500000.0,
                            Status = "Bảo trì",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 18,
                            AssetCode = "EPU-PC-018",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6766), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 19,
                            EmployeeId = 4,
                            IsDeleted = false,
                            Name = "MacBook Air Gen 18",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 20, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6765),
                            PurchasePrice = 19000000.0,
                            Status = "Trong kho",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 19,
                            AssetCode = "EPU-PC-019",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6775), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 20,
                            EmployeeId = 5,
                            IsDeleted = false,
                            Name = "Asus ExpertCenter Gen 19",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 10, 10, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6774),
                            PurchasePrice = 19500000.0,
                            Status = "Hỏng",
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 20,
                            AssetCode = "EPU-PC-020",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6784), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            EmployeeId = 6,
                            IsDeleted = false,
                            Name = "Dell Optiplex Gen 20",
                            Packaging = 0,
                            PurchaseDate = new DateTime(2025, 9, 30, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(6783),
                            PurchasePrice = 20000000.0,
                            Status = "Đang dùng",
                            WarrantyMonths = 24
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(4875), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "CNTT",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà B",
                            Name = "Khoa CNTT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5218), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DT",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà C",
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5227), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "HC",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà D",
                            Name = "Phòng Hành chính"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5232), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "KH",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà A",
                            Name = "Phòng Kế hoạch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5238), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TTTN",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà B",
                            Name = "Trung tâm Thí nghiệm"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5252), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DIEN",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà C",
                            Name = "Khoa Điện"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5257), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "CK",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà D",
                            Name = "Khoa Cơ khí"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5262), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TVU",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà A",
                            Name = "Phòng Tài vụ"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5325), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "TV",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà B",
                            Name = "Thư viện"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5336), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "BV",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà C",
                            Name = "Phòng Bảo vệ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5348), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT11",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà D",
                            Name = "Phòng chức năng 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5355), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT12",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà A",
                            Name = "Phòng chức năng 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5376), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT13",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà B",
                            Name = "Phòng chức năng 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5384), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT14",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà C",
                            Name = "Phòng chức năng 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5443), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT15",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà D",
                            Name = "Phòng chức năng 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5451), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT16",
                            IsDeleted = false,
                            Location = "Tầng 2 - Nhà A",
                            Name = "Phòng chức năng 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5509), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT17",
                            IsDeleted = false,
                            Location = "Tầng 3 - Nhà B",
                            Name = "Phòng chức năng 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5521), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT18",
                            IsDeleted = false,
                            Location = "Tầng 4 - Nhà C",
                            Name = "Phòng chức năng 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5529), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT19",
                            IsDeleted = false,
                            Location = "Tầng 5 - Nhà D",
                            Name = "Phòng chức năng 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5538), new TimeSpan(0, 7, 0, 0, 0)),
                            DeptCode = "DEPT20",
                            IsDeleted = false,
                            Location = "Tầng 1 - Nhà A",
                            Name = "Phòng chức năng 20"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5979), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            Email = "nv1@epu.edu.vn",
                            EmployeeCode = "NV001",
                            FullName = "Nhân viên 1",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(5990), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            Email = "nv2@epu.edu.vn",
                            EmployeeCode = "NV002",
                            FullName = "Nhân viên 2",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6007), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            Email = "nv3@epu.edu.vn",
                            EmployeeCode = "NV003",
                            FullName = "Nhân viên 3",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6015), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            Email = "nv4@epu.edu.vn",
                            EmployeeCode = "NV004",
                            FullName = "Nhân viên 4",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6022), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            Email = "nv5@epu.edu.vn",
                            EmployeeCode = "NV005",
                            FullName = "Nhân viên 5",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6031), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 7,
                            Email = "nv6@epu.edu.vn",
                            EmployeeCode = "NV006",
                            FullName = "Nhân viên 6",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6040), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 8,
                            Email = "nv7@epu.edu.vn",
                            EmployeeCode = "NV007",
                            FullName = "Nhân viên 7",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6048), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 9,
                            Email = "nv8@epu.edu.vn",
                            EmployeeCode = "NV008",
                            FullName = "Nhân viên 8",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6056), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 10,
                            Email = "nv9@epu.edu.vn",
                            EmployeeCode = "NV009",
                            FullName = "Nhân viên 9",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6065), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 1,
                            Email = "nv10@epu.edu.vn",
                            EmployeeCode = "NV010",
                            FullName = "Nhân viên 10",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6073), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 2,
                            Email = "nv11@epu.edu.vn",
                            EmployeeCode = "NV011",
                            FullName = "Nhân viên 11",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6082), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 3,
                            Email = "nv12@epu.edu.vn",
                            EmployeeCode = "NV012",
                            FullName = "Nhân viên 12",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6091), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 4,
                            Email = "nv13@epu.edu.vn",
                            EmployeeCode = "NV013",
                            FullName = "Nhân viên 13",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6098), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 5,
                            Email = "nv14@epu.edu.vn",
                            EmployeeCode = "NV014",
                            FullName = "Nhân viên 14",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(6106), new TimeSpan(0, 7, 0, 0, 0)),
                            DepartmentId = 6,
                            Email = "nv15@epu.edu.vn",
                            EmployeeCode = "NV015",
                            FullName = "Nhân viên 15",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerId = 2,
                            Cost = 150000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7290), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 1",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 17, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7279),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 2,
                            ComputerId = 3,
                            Cost = 200000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7297), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 2",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 16, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7294),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 3,
                            ComputerId = 4,
                            Cost = 250000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7303), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 3",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 15, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7300),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 4,
                            ComputerId = 5,
                            Cost = 300000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7308), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 4",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 14, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7306),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 5,
                            ComputerId = 6,
                            Cost = 350000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7315), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 5",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 13, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7311),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 6,
                            ComputerId = 7,
                            Cost = 400000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7320), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 6",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 12, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7318),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 7,
                            ComputerId = 8,
                            Cost = 450000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7326), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 7",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 11, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7324),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 8,
                            ComputerId = 9,
                            Cost = 500000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7332), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 8",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 10, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7329),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 9,
                            ComputerId = 10,
                            Cost = 550000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7337), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 9",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 9, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7335),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 10,
                            ComputerId = 11,
                            Cost = 600000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7368), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 10",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 8, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7341),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 11,
                            ComputerId = 12,
                            Cost = 650000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7375), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 11",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 7, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7371),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 12,
                            ComputerId = 13,
                            Cost = 700000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7381), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 12",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 6, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7378),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 13,
                            ComputerId = 14,
                            Cost = 750000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7386), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 13",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 5, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7384),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 14,
                            ComputerId = 15,
                            Cost = 800000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7391), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 14",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 4, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7389),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 15,
                            ComputerId = 16,
                            Cost = 850000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7397), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 15",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 3, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7394),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 16,
                            ComputerId = 17,
                            Cost = 900000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7402), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 16",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 2, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7400),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 17,
                            ComputerId = 18,
                            Cost = 950000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7408), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 17",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 4, 1, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7405),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 18,
                            ComputerId = 19,
                            Cost = 1000000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7414), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 18",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 31, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7411),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 19,
                            ComputerId = 20,
                            Cost = 1050000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7419), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 19",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 30, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7417),
                            Status = "Hoàn thành"
                        },
                        new
                        {
                            Id = 20,
                            ComputerId = 1,
                            Cost = 1100000.0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(7425), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bảo trì định kỳ lần thứ 20",
                            IsDeleted = false,
                            RepairDate = new DateTime(2026, 3, 29, 11, 36, 4, 314, DateTimeKind.Local).AddTicks(7422),
                            Status = "Hoàn thành"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 18, 11, 36, 4, 314, DateTimeKind.Unspecified).AddTicks(3485), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "admin@epu.edu.vn",
                            FullName = "Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "$2a$11$xMbJTLJoH82XWAXkuaFk3.aaW9IGvUyrNXgxmp9S0Lnc5KAbTsEV.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Component", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("Components")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Category", "Category")
                        .WithMany("Computers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Computers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("WebQuanLyTaiSan.Models.Employee", "Employee")
                        .WithMany("Computers")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.MaintenanceLog", b =>
                {
                    b.HasOne("WebQuanLyTaiSan.Models.Computer", "Computer")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Computer", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Department", b =>
                {
                    b.Navigation("Computers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebQuanLyTaiSan.Models.Employee", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
